apiVersion: v1
kind: Service
metadata:
  name: my-application
spec:
  selector:
    app: worpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb01_1
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
