apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: my-wordpress
        image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - ps -aux | grep wordpress
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        # livenessProbe:
        # httpGet:
        # path: wp-admin/install.php"
        # port: 80
        # initialDelaySeconds: 5
        # periodSeconds: 10
        # failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "506Mi"
          limits:
            cpu: "500m"
            memory: "516Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb
        - name: WORDPRESS_DB_USER
          value: wpadmindb
        - name: WORDPRESS_DB_PASSWORD
          value: example
        - name: WORDPRESS_DB_NAME
          value: app01db
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
      - name: wordpress
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: wpadmindb
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_DATABASE
          value: app01db
        - name: MYSQL_ROOT_PASSWORD
          value: examplel
          # volumeMounts:
          # - name: mariadb-vol-1
          # mountPath: /var/lib/mysql
      # volumes:
      # - name: mariadb-vol-1
# emptyDir: {}
