apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          value: wpadmindb
        - name: MYSQL_PASSWORD
          value: example
        - name: MYSQL_DATABASE
          value: app01db
        - name: MYSQL_ROOT_PASSWORD
          value: examplel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: mysql-ns
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
