apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-ns
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: mysql-ns
spec:
  selector:
    app: adminer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30000
  type: NodePort
