apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-berrycluster-mariadb-pvclaim
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: berrycluster-mariadb-storageclass
