apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: my-wordpress
        image: wordpress:6.2.1-apache
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "506Mi"
          limits:
            cpu: "500m"
            memory: "516Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb01-1
        - name: WORDPRESS_DB_USER
          value: wpadmindb
        - name: WORDPRESS_DB_PASSWORD
          value: example
        # - name: WORDPRESS_DB_NAME
        # value: app01db
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
      - name: wordpress
        emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb01-1
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb01
        image: mariadb:11.4.1-rc-jammy
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_USER
          value: wpadmindb
        - name: MARIADB_PASSWORD
          value: example
        - name: MARIADB_DATABASE
          value: app01db
        - name: MARIADB_ROOT_PASSWORD
          value: example
        volumeMounts:
        - name: mariadb-vol
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-vol
        emptyDir: {}
